spring.config.import=optional:file:.env[.properties]
spring.application.name=autapi

# Database
spring.datasource.username=root
spring.datasource.password=4ut4p1D3v
spring.datasource.url=jdbc:mysql://localhost:3305/autapi?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
security.jwt.expiration-time=3600000
security.jwt.secret.key=IUFicmFoYW1Fc3Bpbm9zYUBOb2ppcmE=IUFicmFoYW1Fc3Bpbm9zYUBOb2ppcmE=4ut4p1

# Docs
springdoc.swagger-ui.path=/docs
