# Change this file with your development requirements.
spring.config.import=optional:file:.env[.properties]
spring.application.name=autapi

# Database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}
security.jwt.private-key-path=classpath:keys/private-key.pem
security.jwt.public-key-path=classpath:keys/public-key.pem

# Docs
springdoc.swagger-ui.path=/docs
